### ISSUE TITLE
Change Table Naming Structure

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-redshift-sink#15]
When `drop` is `true`:

- CREATE table named after workflow id
- Drop destination table
- Rename workflow id table to destination table name.

Tables shouldn't be dropped before the data fully copies in case of failure.

**Comment by byerc** [comment]
Is there any issue with using a package called "guid" to generate a guid and use that for the temporary name instead of the workflow id?

**Comment by benjamingregory** [comment]
No reason I can think of right now. @schnie, @perryao?

**Comment by byerc** [comment]
Using package `uuid` for consistency.

**Comment by benjamingregory** [comment]
PR here: https://github.com/aries-data/aries-activity-redshift-sink/pull/17
