### ISSUE TITLE
Create Astronomer Index Schema

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-redshift-sink#16]
**Current state:** 
As an end user of the Redshift Sink, I want better insight into how Aries interacts with their db so that I don't need to look through log records of all workflows.

**Proposed solution:**
A quick, easy summary of what actions have been performed in their warehouse, when it occurred, and who authored them. This should be an optional feature to turn off if pure logging is sufficient. 

When each workflow runs, a record of it running should be added to a `workflow_runs` table in the `astronomer_index` schema. 

Possible fields include: `timestamp, table_changed, dropped_or_appended, records added, load_time, workflow_author`

**Comment by schnie** [comment]
@benjamingregory, what was the purpose of this again?  Looks similar to the log data that will be emitted from Aries on every task.

**Comment by benjamingregory** [comment]
Right now the end user has no record of knowing that the activity has finished correctly without going through Astronomer. 

Beyond that - I think theres a general value in having an `astronomer_index` that stores certain metadata from the workflow. Which account authorized the workflow, which source the workflow originates from, What other workflows interact with the same table...all things that give better provenance to the table but are not currently captured in `pg_catalog`.

**Comment by benjamingregory** [comment]
The Redshift Sink might be an inappropriate place to put that, but I think a job adding a record of interaction is warranted.

**Comment by schnie** [comment]
This will be included when we route metrics to elasticsearch search.  This
is the project @alois is currently working on.  It'll log metrics for every
single task that runs.

**Comment by benjamingregory** [comment]
Right - but are the raw records available to the end user? Say I want to create a chart in my personal dashboard detailing the workflow runs into my Redshift from Aries.  Would I then need to create a workflow from Elasticsearch to Redshift to copy over the records?

**Comment by schnie** [comment]
The plan would be to deliver this data as part of the monitoring
interface.  Are you thinking that we would dump these records into a
separate schema within the users redshift?

**Comment by benjamingregory** [comment]
Yeah thats what I was thinking. I think broadly there's a need both the raw records (which we include) and metadata associated with it in the same place.

I'll conceptualize it a bit more and present what I'm thinking to you and Mike.
